version: '3.8'

services:

  #web:
  #  restart: always
  #  build:
  #    context: ./
  #    dockerfile: Dockerfile
  #  ports:
  #   - '3000:3000'
  #   - '3001:3001'
  # networks:
  #   - mynetwork
  # depends_on:
  #   - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - mynetwork
volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
