FROM oven/bun:latest as build
WORKDIR /app

COPY package.json ./
COPY bun.lockb ./
COPY tsconfig.json ./
COPY tsconfig.node.json ./
COPY startup.sh ./

# !! Copy prisma modules. Cringe, i know
COPY node_modules ./node_modules
RUN bun install --production

COPY ./server ./server
COPY ./shared ./shared

RUN bun run build:server

RUN chmod +x startup.sh
CMD ["/bin/sh", "startup.sh" ]
