-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "calories" SET DATA TYPE REAL,
ALTER COLUMN "protein" SET DATA TYPE REAL,
ALTER COLUMN "fats" SET DATA TYPE REAL,
ALTER COLUMN "carbohydrates" SET DATA TYPE REAL;
