export enum Roles {
	ADMIN = 'ADMIN',
	DEFAULT = 'DEFAULT',
}

export enum Currencies {
	USD = 'USD',
	BYN = 'BYN',
	RUB = 'RUB',
}

export enum RecipeTypes {
	VEGETARIAN = 'VEGETARIAN',
	PASTRIES = 'PASTRIES',
	GARNISHES = 'GARNISHES',
	HOTDISHES = 'HOTDISHES',
	HOTAPPETIZERS = 'HOTAPPETIZERS',
	DESSERTS = 'DESSERTS',
	HOMEMADE = 'HOMEMADE',
	BREAKFASTS = 'BREAKFASTS',
	PRESERVES = 'PRESERVES',
	CHARCOAL = 'CHARCOAL',
	BEVERAGES = 'BEVERAGES',
	SALADS = 'SALADS',
	SAUCESPASTASDRESSINGS = 'SAUCESPASTASDRESSINGS',
	SOUPSBROTHS = 'SOUPSBROTHS',
	DOUGHS = 'DOUGHS',
	BREAD = 'BREAD',
	COLDAPPETIZERS = 'COLDAPPETIZERS',
	SHASHLIKS = 'SHASHLIKS',
}

export enum Units {
	GRAMS = 'GRAMS',
	KILOGRAMS = 'KILOGRAMS',
	ITEMS = 'ITEMS',
	PIECES = 'PIECES',
}
