name: VF-BACKEND

on:
  push:
    branches: [ "master","migrate-to-bun" ]
  pull_request:
    branches: [ "master","migrate-to-bun" ]

jobs:
  server_build:
    name: server build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: sudo bun install
      - run: sudo bun run build:server
      - run: sudo bun run prisma_gen
